from typing import Protocol


class TorrentClient(Protocol):
    provider_id: str
    display_name: str
    scope_name: str
    supports_delete_data: bool

    async def close(self) -> None: ...

    async def version(self) -> str: ...

    async def scopes(self) -> list[str]: ...

    async def torrents(self) -> list[dict]: ...

    async def files(self, torrent_hash: str) -> list[dict]: ...

    async def resume(self, torrent_hash: str) -> None: ...

    async def delete(self, torrent_hash: str, delete_files: bool) -> None: ...
